export const avatarMap: Record<string, any> = {
  // 🧠 ANIME AVATARS
  "/avatars/anime/anime1.jpg": require("@/assets/images/avatars/anime/anime1.jpg"),
  "/avatars/anime/anime2.jpg": require("@/assets/images/avatars/anime/anime2.jpg"),
  "/avatars/anime/anime3.jpg": require("@/assets/images/avatars/anime/anime3.jpg"),
  "/avatars/anime/anime4.jpg": require("@/assets/images/avatars/anime/anime4.jpg"),
  "/avatars/anime/anime5.jpg": require("@/assets/images/avatars/anime/anime5.jpg"),
  "/avatars/anime/anime6.jpg": require("@/assets/images/avatars/anime/anime6.jpg"),
  "/avatars/anime/anime7.jpg": require("@/assets/images/avatars/anime/anime7.jpg"),
  "/avatars/anime/anime8.jpg": require("@/assets/images/avatars/anime/anime8.jpg"),
  "/avatars/anime/anime9.jpg": require("@/assets/images/avatars/anime/anime9.jpg"),
  "/avatars/anime/anime10.jpg": require("@/assets/images/avatars/anime/anime10.jpg"),
  "/avatars/anime/anime11.jpg": require("@/assets/images/avatars/anime/anime11.jpg"),
  "/avatars/anime/anime12.jpg": require("@/assets/images/avatars/anime/anime12.jpg"),

  // 🎩 CLASSIC AVATARS
  "/avatars/classic/classic1.png": require("@/assets/images/avatars/classic/classic1.png"),
  "/avatars/classic/classic2.png": require("@/assets/images/avatars/classic/classic2.png"),
  "/avatars/classic/classic3.png": require("@/assets/images/avatars/classic/classic3.png"),
  "/avatars/classic/classic4.png": require("@/assets/images/avatars/classic/classic4.png"),
  "/avatars/classic/classic5.png": require("@/assets/images/avatars/classic/classic5.png"),
  "/avatars/classic/classic6.jpg": require("@/assets/images/avatars/classic/classic6.jpg"),
  "/avatars/classic/classic7.jpg": require("@/assets/images/avatars/classic/classic7.jpg"),
  "/avatars/classic/classic8.jpg": require("@/assets/images/avatars/classic/classic8.jpg"),
  "/avatars/classic/classic9.jpg": require("@/assets/images/avatars/classic/classic9.jpg"),
  "/avatars/classic/classic10.jpg": require("@/assets/images/avatars/classic/classic10.jpg"),
  "/avatars/classic/classic11.jpg": require("@/assets/images/avatars/classic/classic11.jpg"),
  "/avatars/classic/classic12.jpg": require("@/assets/images/avatars/classic/classic12.jpg"),

  // 😎 FUNKY AVATARS
  "/avatars/funky/funky1.png": require("@/assets/images/avatars/funky/funky1.png"),
  "/avatars/funky/funky2.jpg": require("@/assets/images/avatars/funky/funky2.jpg"),
  "/avatars/funky/funky3.jpg": require("@/assets/images/avatars/funky/funky3.jpg"),
  "/avatars/funky/funky4.jpg": require("@/assets/images/avatars/funky/funky4.jpg"),
  "/avatars/funky/funky5.jpg": require("@/assets/images/avatars/funky/funky5.jpg"),
  "/avatars/funky/funky6.png": require("@/assets/images/avatars/funky/funky6.png"),
  "/avatars/funky/funky7.jpg": require("@/assets/images/avatars/funky/funky7.jpg"),
  "/avatars/funky/funky8.jpg": require("@/assets/images/avatars/funky/funky8.jpg"),
  "/avatars/funky/funky9.jpg": require("@/assets/images/avatars/funky/funky9.jpg"),
  "/avatars/funky/funky10.jpg": require("@/assets/images/avatars/funky/funky10.jpg"),
  "/avatars/funky/funky11.jpg": require("@/assets/images/avatars/funky/funky11.jpg"),
  "/avatars/funky/funky12.jpg": require("@/assets/images/avatars/funky/funky12.jpg"),

  // 🤪 INSANE AVATARS
  "/avatars/insane/insane1.jpg": require("@/assets/images/avatars/insane/insane1.jpg"),
  "/avatars/insane/insane2.jpg": require("@/assets/images/avatars/insane/insane2.jpg"),
  "/avatars/insane/insane3.jpg": require("@/assets/images/avatars/insane/insane3.jpg"),
  "/avatars/insane/insane4.jpg": require("@/assets/images/avatars/insane/insane4.jpg"),
  "/avatars/insane/insane5.jpg": require("@/assets/images/avatars/insane/insane5.jpg"),
  "/avatars/insane/insane6.jpg": require("@/assets/images/avatars/insane/insane6.jpg"),
  "/avatars/insane/insane7.jpg": require("@/assets/images/avatars/insane/insane7.jpg"),
  "/avatars/insane/insane8.jpg": require("@/assets/images/avatars/insane/insane8.jpg"),
  "/avatars/insane/insane9.jpg": require("@/assets/images/avatars/insane/insane9.jpg"),
  "/avatars/insane/insane10.jpg": require("@/assets/images/avatars/insane/insane10.jpg"),
  "/avatars/insane/insane11.jpg": require("@/assets/images/avatars/insane/insane11.jpg"),
  "/avatars/insane/insane12.jpg": require("@/assets/images/avatars/insane/insane12.jpg"),
  "/avatars/insane/insane13.jpg": require("@/assets/images/avatars/insane/insane13.jpg"),
  "/avatars/insane/insane14.jpg": require("@/assets/images/avatars/insane/insane14.jpg"),
  "/avatars/insane/insane15.jpg": require("@/assets/images/avatars/insane/insane15.jpg"),

  // 🕰️ OLD AVATARS
  "/avatars/old/avatar1.png": require("@/assets/images/avatars/old/avatar1.png"),
  "/avatars/old/avatar2.png": require("@/assets/images/avatars/old/avatar2.png"),
  "/avatars/old/avatar3.png": require("@/assets/images/avatars/old/avatar3.png"),
};
